# Generated by Django 4.0.1 on 2022-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('cookies', models.CharField(max_length=500)),
                ('uuid', models.CharField(max_length=200)),
                ('post_id', models.IntegerField()),
                ('post_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='params',
        ),
    ]
