# Generated by Django 4.0.1 on 2022-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0002_api_params_delete_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_params',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
