# Generated by Django 4.0.1 on 2022-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0004_alter_api_params_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_params',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='api_params',
            name='uuid',
        ),
        migrations.AddField(
            model_name='api_params',
            name='c_user',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='api_params',
            name='c_user_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='api_params',
            name='xs',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='api_params',
            name='xs_time',
            field=models.IntegerField(default=None),
        ),
    ]
