# Generated by Django 4.0.1 on 2022-01-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0005_remove_api_params_cookies_remove_api_params_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_params',
            name='post_id',
        ),
        migrations.AddField(
            model_name='api_params',
            name='uuid',
            field=models.UUIDField(default=None),
        ),
    ]
