# Generated by Django 4.0.1 on 2022-01-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0006_remove_api_params_post_id_api_params_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_params',
            name='url',
        ),
    ]
