# Generated by Django 4.0.1 on 2022-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0007_remove_api_params_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_params',
            name='post_url',
        ),
        migrations.AddField(
            model_name='api_params',
            name='post_id',
            field=models.IntegerField(default=None),
        ),
    ]
