# Generated by Django 4.0.1 on 2022-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0009_api_params_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_params',
            name='port',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
