# Generated by Django 4.0.1 on 2022-01-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0011_alter_api_params_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='join_grp_api_params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default=None, max_length=50)),
                ('xs', models.CharField(default=None, max_length=200)),
                ('xs_time', models.IntegerField(default=None)),
                ('c_user', models.CharField(default=None, max_length=200)),
                ('c_user_time', models.IntegerField(default=None)),
                ('uuid', models.UUIDField(default=None)),
                ('grp_list', models.CharField(default=None, max_length=1000)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
