# Generated by Django 4.0.1 on 2022-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0012_join_grp_api_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_grp_api_params',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
