# Generated by Django 4.0.1 on 2022-01-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0013_join_grp_api_params_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_grp_api_params',
            name='uu',
            field=models.JSONField(default=None),
        ),
    ]
