# Generated by Django 4.0.1 on 2022-01-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0014_join_grp_api_params_uu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_grp_api_params',
            name='uu',
        ),
    ]
