# Generated by Django 4.0.1 on 2022-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0015_remove_join_grp_api_params_uu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_params',
            name='c_user_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='port',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='post_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='api_params',
            name='xs_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='join_grp_api_params',
            name='c_user_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='join_grp_api_params',
            name='port',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='join_grp_api_params',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='join_grp_api_params',
            name='xs_time',
            field=models.CharField(max_length=50),
        ),
    ]
