# Generated by Django 4.0.2 on 2022-02-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0016_alter_api_params_c_user_time_alter_api_params_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_cookies_api_params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_password', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(default=None, max_length=200)),
                ('fb_password', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
